name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Replace with your default branch name if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Build the Jekyll site using actions/jekyll-build-pages
      - name: Build Jekyll site
        uses: actions/jekyll-build-pages@v1
        with:
          source: .
          destination: ./_site

      # Step 3: Upload site to GitHub Pages
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
